apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bookinfo-ratings-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: ratings 
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: version
                operator: In
                values:
                  - v2
                  - v3 
      ports:
        - protocol: TCP
          port: 9080